stages:
- stage: Deploy
  displayName: DeployStage
  jobs:
  - deployment: VMDeploy
    displayName: inca-dev
    pool:
      vmImage: 'Ubuntu-18.04'
    environment:
      name: nexxt-inca-env
      resourceType: VirtualMachine
    strategy:
        runOnce:
          deploy:
            steps:
            - script: echo my first deployment on nexxt-inca-env
            - script: touch touchedFile